### PR TITLE
Handle .git location for submodules

### PR DESCRIPTION
**Pull request by ryan-kimber**
If .git is actually a file and not a directory, we're in a submodule and .git is actually a 'pointer' file that tells us where the actual .git dir contents are.

This change checks to see if the file is a directory and, if it's not, naively loads the contents of the file assuming it only contains 'gitdir: <directory location>'

### CODE REVIEW

**Comment by ryan-kimber** [comment]
Hmm. Build & Tests work locally, but fail here complaining of 'internalModule' function. I can't find any references to that in the module or test source files. Also, the same command that is run before the fail in Travis (mocha spec/*-spec.js src/**/*-spec.js), runs fine locally, producing 16 passed tests.

bahmutov, unless you can take a look, I'll be relying on my own patched fork for now.

**Comment by bahmutov** [comment]
oh, this could be due to different travis node version :( I will merge and take a look, thank you very much for looking into this

**Comment by bahmutov** [comment]
released as v1.9.0 - thank you very much for the pull request

**Comment by ryan-kimber** [comment]
Thanks for getting it merged in. I'm always happy to have one less forked
dependency in our projects.

**Comment by bahmutov** [comment]
I feel the same way, let me know if something does not work. The git integration is hard to test, especially with hooks in pre-git

**Pull request merged**
